apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: credit-card-backend:latest
        ports:
        - containerPort: 8080
