apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: credit-card-frontend:latest
        ports:
        - containerPort: 3000
